local assetSheets = LoadModule("Scripts/ScriptResources/AssetSheets")
local uiImagesFile = "art/uiimages1.txt"

local function isValidSkillDisplayName(name)
	if not name then
		return false
	end
	if name == "" then
		return false
	end
	if name:find("DNT") then
		return false
	end
	if name:find("UNUSED") then
		return false
	end
	if name:find("%?%?%?") then
		return false
	end
	return true
end

local function commonMetadata(alias)
	-- x, y, w, h may also be added by addToSheet later
	return {
		alias = alias,
	}
end

main.skillAssetCacheExtract = main.skillAssetCacheExtract or { }
main.assetCacheExtract = main.assetCacheExtract or { }
main.ggpk:ExtractList({ uiImagesFile }, main.assetCacheExtract)
local uiImages = assetSheets.parseUIImages(uiImagesFile)
local assetPath = GetWorkDir() .. "/../Data/Skills/"
MakeDir(assetPath)
local defaultMaxWidth = 1500
local sheets = {
	assetSheets.newSheet("gem-icons", defaultMaxWidth, 100),
	assetSheets.newSheet("gem-backgrounds", defaultMaxWidth, 100),
}
local function getSheet(name)
	return name == "gem-icons" and sheets[1] or sheets[2]
end

for skill in dat("ActiveSkills"):Rows() do
	if skill.Icon ~= "" and isValidSkillDisplayName(skill.DisplayName) then
		assetSheets.addToSheet(getSheet("gem-icons"), string.lower(skill.Icon), "gem-icons", commonMetadata(skill.Icon))
	end
end

for skillGem in dat("SkillGems"):Rows() do
	if skillGem.HoverImage ~= "" then
		local name
		for _, effect in pairs(skillGem.GemEffects) do
			name = effect.GrantedEffect.Id
		end
		-- 0.5.5 changed HoverImage from a texture path to a UI image name
		local hoverImage = skillGem.HoverImage
		if not hoverImage:lower():match("%.dds$") then
			local asset = uiImages[string.lower(hoverImage)]
			hoverImage = asset and asset.path
		end
		assetSheets.addToSheet(getSheet("gem-backgrounds"), hoverImage, "gem-backgrounds", commonMetadata(name))
	end
end

local skillAssets = {
	ddsCoords = { },
}
assetSheets.extractSheetFiles(sheets, false, nil, main.skillAssetCacheExtract)
for _, sheet in ipairs(sheets) do
	assetSheets.calculateDDSPack(sheet, main.ggpk.oozPath, assetPath, false)
	for file, fileInfo in pairs(sheet.ddsCoords) do
		skillAssets.ddsCoords[file] = fileInfo
	end
end

local out = io.open("../Data/Skills/SkillAssets.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Skill image data (c) Grinding Gear Games\n\nreturn ')
writeLuaTable(out, skillAssets, 1)
out:close()

local assets = {
	ddsCoords = { },
}
local monsterCategorySheet = assetSheets.newSheet("monster-categories", defaultMaxWidth, 100)
for category in dat("MonsterCategories"):Rows() do
	if not category.Type:find("^%[DNT") then
		local asset = uiImages[string.lower(category.HudImage)]
		assetSheets.addToSheet(monsterCategorySheet, asset.path, "monster-categories", commonMetadata(category.Type))
	end
end

assetSheets.extractSheetFiles({ monsterCategorySheet }, false, nil, main.assetCacheExtract)
MakeDir(GetWorkDir() .. "/../Assets/")
assetSheets.calculateDDSPack(monsterCategorySheet, main.ggpk.oozPath, GetWorkDir() .. "/../Assets/", false)
for file, fileInfo in pairs(monsterCategorySheet.ddsCoords) do
	assets.ddsCoords[file] = fileInfo
end

out = io.open("../Data/Assets.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Image data (c) Grinding Gear Games\n\nreturn ')
writeLuaTable(out, assets, 1)
out:close()
