-- This file is automatically generated, do not edit!
-- Game data (c) Grinding Gear Games

-- Default skill gem base item IDs keyed by main-hand and off-hand WieldableClasses item class IDs.

-- spell-checker: disable
return {
	["Bow"] = {
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultBow",
		},
	},
	["Claw"] = {
		["Claw"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultClawClaw",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultClaw",
		},
	},
	["Crossbow"] = {
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultCrossbow",
		},
	},
	["Dagger"] = {
		["Dagger"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultDaggerDagger",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultDagger",
		},
	},
	["Flail"] = {
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultFlail",
		},
	},
	["One Hand Axe"] = {
		["One Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultAxeAxe",
		},
		["Two Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultAxeAxe",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HAxe",
		},
	},
	["One Hand Mace"] = {
		["One Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultMaceMace",
		},
		["Two Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultMaceMace",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HMace",
		},
	},
	["One Hand Sword"] = {
		["One Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSwordSword",
		},
		["Two Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSwordSword",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HSword",
		},
	},
	["Spear"] = {
		["Buckler"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSpearOffHand",
			"Metadata/Items/Gem/SkillGemPlayerDefaultSpearThrow",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSpear",
			"Metadata/Items/Gem/SkillGemPlayerDefaultSpearThrow",
		},
	},
	["Talisman"] = {
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultUnarmed",
		},
	},
	["Two Hand Axe"] = {
		["One Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultAxeAxe",
		},
		["Two Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultAxeAxe",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault2HAxe",
		},
	},
	["Two Hand Mace"] = {
		["One Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultMaceMace",
		},
		["Two Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultMaceMace",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault2HMace",
		},
	},
	["Two Hand Sword"] = {
		["One Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSwordSword",
		},
		["Two Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultSwordSword",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault2HSword",
		},
	},
	["Unarmed"] = {
		["Claw"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultClaw",
		},
		["Dagger"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultDagger",
		},
		["One Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HAxe",
		},
		["One Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HMace",
		},
		["One Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HSword",
		},
		["Two Hand Axe"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HAxe",
		},
		["Two Hand Mace"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HMace",
		},
		["Two Hand Sword"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefault1HSword",
		},
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultUnarmed",
		},
	},
	["Warstaff"] = {
		["Unarmed"] = {
			"Metadata/Items/Gem/SkillGemPlayerDefaultQuarterstaff",
		},
	},
}
